include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    lines_longer_than_80_chars: ignore
    unnecessary_lambdas: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    require_trailing_commas: ignore

linter:
  rules:
    public_member_api_docs: false
