name: my_portfolio_web
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_carousel_widget: ^3.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  intl: ^0.19.0
  timeline_tile: ^2.0.0
  url_launcher: ^6.2.4

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mockito: ^5.4.6
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cv/
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/tile_images/
    - assets/tech_icon_svg/

  # Using Google Fonts instead of local fonts
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700
