// Mocks generated by Mockito 5.4.4 from annotations
// in my_portfolio_web/test/app/controllers/controller_factory_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i6;

import 'package:flutter/material.dart' as _i2;
import 'package:get/get.dart' as _i3;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:my_portfolio_web/app/controllers/career_controller.dart'
    as _i10;
import 'package:my_portfolio_web/app/controllers/contact_controller.dart'
    as _i11;
import 'package:my_portfolio_web/app/controllers/navigation_controller.dart'
    as _i4;
import 'package:my_portfolio_web/app/controllers/projects_controller.dart'
    as _i7;
import 'package:my_portfolio_web/app/controllers/skills_controller.dart'
    as _i12;
import 'package:my_portfolio_web/app/controllers/theme_controller.dart' as _i14;
import 'package:my_portfolio_web/app/data/models/tech_stack_item.dart' as _i13;
import 'package:my_portfolio_web/app/data/repositories/portfolio_repository.dart'
    as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeScrollController_0 extends _i1.SmartFake
    implements _i2.ScrollController {
  _FakeScrollController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGlobalKey_1<T extends _i2.State<_i2.StatefulWidget>>
    extends _i1.SmartFake implements _i2.GlobalKey<T> {
  _FakeGlobalKey_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxString_2 extends _i1.SmartFake implements _i3.RxString {
  _FakeRxString_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternalFinalCallback_3<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRxBool_4 extends _i1.SmartFake implements _i3.RxBool {
  _FakeRxBool_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRx_5<T> extends _i1.SmartFake implements _i3.Rx<T> {
  _FakeRx_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_6 extends _i1.SmartFake implements _i2.ThemeData {
  _FakeThemeData_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [NavigationController].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationController extends _i1.Mock
    implements _i4.NavigationController {
  MockNavigationController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ScrollController get scrollController => (super.noSuchMethod(
        Invocation.getter(#scrollController),
        returnValue: _FakeScrollController_0(
          this,
          Invocation.getter(#scrollController),
        ),
      ) as _i2.ScrollController);

  @override
  _i2.GlobalKey<_i2.State<_i2.StatefulWidget>> get aboutKey =>
      (super.noSuchMethod(
        Invocation.getter(#aboutKey),
        returnValue: _FakeGlobalKey_1<_i2.State<_i2.StatefulWidget>>(
          this,
          Invocation.getter(#aboutKey),
        ),
      ) as _i2.GlobalKey<_i2.State<_i2.StatefulWidget>>);

  @override
  _i2.GlobalKey<_i2.State<_i2.StatefulWidget>> get educationKey =>
      (super.noSuchMethod(
        Invocation.getter(#educationKey),
        returnValue: _FakeGlobalKey_1<_i2.State<_i2.StatefulWidget>>(
          this,
          Invocation.getter(#educationKey),
        ),
      ) as _i2.GlobalKey<_i2.State<_i2.StatefulWidget>>);

  @override
  _i2.GlobalKey<_i2.State<_i2.StatefulWidget>> get skillsKey =>
      (super.noSuchMethod(
        Invocation.getter(#skillsKey),
        returnValue: _FakeGlobalKey_1<_i2.State<_i2.StatefulWidget>>(
          this,
          Invocation.getter(#skillsKey),
        ),
      ) as _i2.GlobalKey<_i2.State<_i2.StatefulWidget>>);

  @override
  _i2.GlobalKey<_i2.State<_i2.StatefulWidget>> get projectsKey =>
      (super.noSuchMethod(
        Invocation.getter(#projectsKey),
        returnValue: _FakeGlobalKey_1<_i2.State<_i2.StatefulWidget>>(
          this,
          Invocation.getter(#projectsKey),
        ),
      ) as _i2.GlobalKey<_i2.State<_i2.StatefulWidget>>);

  @override
  _i2.GlobalKey<_i2.State<_i2.StatefulWidget>> get careerKey =>
      (super.noSuchMethod(
        Invocation.getter(#careerKey),
        returnValue: _FakeGlobalKey_1<_i2.State<_i2.StatefulWidget>>(
          this,
          Invocation.getter(#careerKey),
        ),
      ) as _i2.GlobalKey<_i2.State<_i2.StatefulWidget>>);

  @override
  _i2.GlobalKey<_i2.State<_i2.StatefulWidget>> get contactKey =>
      (super.noSuchMethod(
        Invocation.getter(#contactKey),
        returnValue: _FakeGlobalKey_1<_i2.State<_i2.StatefulWidget>>(
          this,
          Invocation.getter(#contactKey),
        ),
      ) as _i2.GlobalKey<_i2.State<_i2.StatefulWidget>>);

  @override
  _i3.RxString get activeSection => (super.noSuchMethod(
        Invocation.getter(#activeSection),
        returnValue: _FakeRxString_2(
          this,
          Invocation.getter(#activeSection),
        ),
      ) as _i3.RxString);

  @override
  List<String> get animatedGreetings => (super.noSuchMethod(
        Invocation.getter(#animatedGreetings),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get animatedIntroductions => (super.noSuchMethod(
        Invocation.getter(#animatedIntroductions),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void initializeController() => super.noSuchMethod(
        Invocation.method(
          #initializeController,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cleanupResources() => super.noSuchMethod(
        Invocation.method(
          #cleanupResources,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scrollToSection(String? section) => super.noSuchMethod(
        Invocation.method(
          #scrollToSection,
          [section],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListener(_i5.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i6.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListenerId(
    Object? key,
    _i5.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ProjectsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsController extends _i1.Mock
    implements _i7.ProjectsController {
  MockProjectsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.RxBool get isCarouselPlaying => (super.noSuchMethod(
        Invocation.getter(#isCarouselPlaying),
        returnValue: _FakeRxBool_4(
          this,
          Invocation.getter(#isCarouselPlaying),
        ),
      ) as _i3.RxBool);

  @override
  String get fallbackImageUrl => (super.noSuchMethod(
        Invocation.getter(#fallbackImageUrl),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#fallbackImageUrl),
        ),
      ) as String);

  @override
  List<Map<String, String>> get projects => (super.noSuchMethod(
        Invocation.getter(#projects),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void initializeController() => super.noSuchMethod(
        Invocation.method(
          #initializeController,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cleanupResources() => super.noSuchMethod(
        Invocation.method(
          #cleanupResources,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getImageWithFallback(String? imagePath) => (super.noSuchMethod(
        Invocation.method(
          #getImageWithFallback,
          [imagePath],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getImageWithFallback,
            [imagePath],
          ),
        ),
      ) as String);

  @override
  _i9.Future<void> launchProjectUrl(String? url) => (super.noSuchMethod(
        Invocation.method(
          #launchProjectUrl,
          [url],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void toggleCarouselPlay() => super.noSuchMethod(
        Invocation.method(
          #toggleCarouselPlay,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListener(_i5.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i6.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListenerId(
    Object? key,
    _i5.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CareerController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCareerController extends _i1.Mock implements _i10.CareerController {
  MockCareerController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, String>> get careerTimeline => (super.noSuchMethod(
        Invocation.getter(#careerTimeline),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  List<Map<String, String>> get educationInfo => (super.noSuchMethod(
        Invocation.getter(#educationInfo),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  String get professionalSummary => (super.noSuchMethod(
        Invocation.getter(#professionalSummary),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#professionalSummary),
        ),
      ) as String);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void initializeController() => super.noSuchMethod(
        Invocation.method(
          #initializeController,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cleanupResources() => super.noSuchMethod(
        Invocation.method(
          #cleanupResources,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListener(_i5.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i6.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListenerId(
    Object? key,
    _i5.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ContactController].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactController extends _i1.Mock implements _i11.ContactController {
  MockContactController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get contactInfo => (super.noSuchMethod(
        Invocation.getter(#contactInfo),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Map<String, Map<String, dynamic>> get socialLinks => (super.noSuchMethod(
        Invocation.getter(#socialLinks),
        returnValue: <String, Map<String, dynamic>>{},
      ) as Map<String, Map<String, dynamic>>);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void initializeController() => super.noSuchMethod(
        Invocation.method(
          #initializeController,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cleanupResources() => super.noSuchMethod(
        Invocation.method(
          #cleanupResources,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<void> launchEmail() => (super.noSuchMethod(
        Invocation.method(
          #launchEmail,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> launchWhatsApp() => (super.noSuchMethod(
        Invocation.method(
          #launchWhatsApp,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> downloadCV() => (super.noSuchMethod(
        Invocation.method(
          #downloadCV,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void copyToClipboard(String? text) => super.noSuchMethod(
        Invocation.method(
          #copyToClipboard,
          [text],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListener(_i5.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i6.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListenerId(
    Object? key,
    _i5.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SkillsController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSkillsController extends _i1.Mock implements _i12.SkillsController {
  MockSkillsController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i13.TechStackItem> get techStack => (super.noSuchMethod(
        Invocation.getter(#techStack),
        returnValue: <_i13.TechStackItem>[],
      ) as List<_i13.TechStackItem>);

  @override
  List<Map<String, dynamic>> get skillCategories => (super.noSuchMethod(
        Invocation.getter(#skillCategories),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<String> get skills => (super.noSuchMethod(
        Invocation.getter(#skills),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void initializeController() => super.noSuchMethod(
        Invocation.method(
          #initializeController,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cleanupResources() => super.noSuchMethod(
        Invocation.method(
          #cleanupResources,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListener(_i5.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i6.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListenerId(
    Object? key,
    _i5.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ThemeController].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeController extends _i1.Mock implements _i14.ThemeController {
  MockThemeController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Rx<_i2.ThemeMode> get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _FakeRx_5<_i2.ThemeMode>(
          this,
          Invocation.getter(#themeMode),
        ),
      ) as _i3.Rx<_i2.ThemeMode>);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
      ) as bool);

  @override
  _i2.ThemeData get currentTheme => (super.noSuchMethod(
        Invocation.getter(#currentTheme),
        returnValue: _FakeThemeData_6(
          this,
          Invocation.getter(#currentTheme),
        ),
      ) as _i2.ThemeData);

  @override
  _i3.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_3<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int get listeners => (super.noSuchMethod(
        Invocation.getter(#listeners),
        returnValue: 0,
      ) as int);

  @override
  void toggleTheme() => super.noSuchMethod(
        Invocation.method(
          #toggleTheme,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void initializeController() => super.noSuchMethod(
        Invocation.method(
          #initializeController,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void cleanupResources() => super.noSuchMethod(
        Invocation.method(
          #cleanupResources,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void update([
    List<Object>? ids,
    bool? condition = true,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #update,
          [
            ids,
            condition,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListener(_i5.GetStateUpdate? listener) => (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refresh() => super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
        Invocation.method(
          #refreshGroup,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyChildrens() => super.noSuchMethod(
        Invocation.method(
          #notifyChildrens,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListenerId(
    Object? id,
    _i6.VoidCallback? listener,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #removeListenerId,
          [
            id,
            listener,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Disposer addListenerId(
    Object? key,
    _i5.GetStateUpdate? listener,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListenerId,
          [
            key,
            listener,
          ],
        ),
        returnValue: () {},
      ) as _i5.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
        Invocation.method(
          #disposeId,
          [id],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PortfolioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioRepository extends _i1.Mock
    implements _i15.PortfolioRepository {
  MockPortfolioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i13.TechStackItem> getTechStack() => (super.noSuchMethod(
        Invocation.method(
          #getTechStack,
          [],
        ),
        returnValue: <_i13.TechStackItem>[],
      ) as List<_i13.TechStackItem>);

  @override
  Map<String, Map<String, dynamic>> getSocialLinks() => (super.noSuchMethod(
        Invocation.method(
          #getSocialLinks,
          [],
        ),
        returnValue: <String, Map<String, dynamic>>{},
      ) as Map<String, Map<String, dynamic>>);

  @override
  List<String> getAnimatedGreetings() => (super.noSuchMethod(
        Invocation.method(
          #getAnimatedGreetings,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> getAnimatedIntroductions() => (super.noSuchMethod(
        Invocation.method(
          #getAnimatedIntroductions,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> getDesignPhilosophyQuotes() => (super.noSuchMethod(
        Invocation.method(
          #getDesignPhilosophyQuotes,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<Map<String, dynamic>> getSkillCategories() => (super.noSuchMethod(
        Invocation.method(
          #getSkillCategories,
          [],
        ),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);

  @override
  List<Map<String, String>> getProjects() => (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [],
        ),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  List<Map<String, String>> getCareerTimeline() => (super.noSuchMethod(
        Invocation.method(
          #getCareerTimeline,
          [],
        ),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  Map<String, String> getContactInfo() => (super.noSuchMethod(
        Invocation.method(
          #getContactInfo,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  List<Map<String, String>> getEducationInfo() => (super.noSuchMethod(
        Invocation.method(
          #getEducationInfo,
          [],
        ),
        returnValue: <Map<String, String>>[],
      ) as List<Map<String, String>>);

  @override
  String getProfessionalSummary() => (super.noSuchMethod(
        Invocation.method(
          #getProfessionalSummary,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getProfessionalSummary,
            [],
          ),
        ),
      ) as String);
}
